public class sampleLooping {
    public static void main(String[] args) {
        int i = 0;
        String bincode = "";
        while (i <= 182) {
            switch (i) {
            case 0: bincode = "aa";
            break;
            case 1: bincode = "ab";
            break;
            case 2: bincode = "ae";
            break;
            case 3: bincode = "af";
            break;
            case 4: bincode = "ak";
            break;
            case 5: bincode = "am";
            break;
            case 6: bincode = "an";
            break;
            case 7: bincode = "ar";
            break;
            case 8: bincode = "as";
            break;
            case 9: bincode = "av";
            break;
            case 10: bincode = "ay";
            break;
            case 11: bincode = "az";
            break;
            case 12: bincode = "ba";
            break;
            case 13: bincode = "be";
            break;
            case 14: bincode = "bg";
            break;
            case 15: bincode = "bi";
            break;
            case 16: bincode = "bm";
            break;
            case 17: bincode = "bn";
            break;
            case 18: bincode = "bo";
            break;
            case 19: bincode = "br";
            break;
            case 20: bincode = "bs";
            break;
            case 21: bincode = "ca";
            break;
            case 22: bincode = "ce";
            break;
            case 23: bincode = "ch";
            break;
            case 24: bincode = "co";
            break;
            case 25: bincode = "cr";
            break;
            case 26: bincode = "cs";
            break;
            case 27: bincode = "cu";
            break;
            case 28: bincode = "cv";
            break;
            case 29: bincode = "cy";
            break;
            case 30: bincode = "da";
            break;
            case 31: bincode = "de";
            break;
            case 32: bincode = "dv";
            break;
            case 33: bincode = "dz";
            break;
            case 34: bincode = "ee";
            break;
            case 35: bincode = "el";
            break;
            case 36: bincode = "en";
            break;
            case 37: bincode = "eo";
            break;
            case 38: bincode = "es";
            break;
            case 39: bincode = "et";
            break;
            case 40: bincode = "eu";
            break;
            case 41: bincode = "fa";
            break;
            case 42: bincode = "ff";
            break;
            case 43: bincode = "fi";
            break;
            case 44: bincode = "fj";
            break;
            case 45: bincode = "fo";
            break;
            case 46: bincode = "fr";
            break;
            case 47: bincode = "fy";
            break;
            case 48: bincode = "ga";
            break;
            case 49: bincode = "gd";
            break;
            case 50: bincode = "gl";
            break;
            case 51: bincode = "gn";
            break;
            case 52: bincode = "gu";
            break;
            case 53: bincode = "gv";
            break;
            case 54: bincode = "ha";
            break;
            case 55: bincode = "he";
            break;
            case 56: bincode = "hi";
            break;
            case 57: bincode = "ho";
            break;
            case 58: bincode = "hr";
            break;
            case 59: bincode = "ht";
            break;
            case 60: bincode = "hu";
            break;
            case 61: bincode = "hy";
            break;
            case 62: bincode = "hz";
            break;
            case 63: bincode = "ia";
            break;
            case 64: bincode = "id";
            break;
            case 65: bincode = "zu";
            break;
            case 66: bincode = "ie";
            break;
            case 67: bincode = "ig";
            break;
            case 68: bincode = "ii";
            break;
            case 69: bincode = "ik";
            break;
            case 70: bincode = "io";
            break;
            case 71: bincode = "is";
            break;
            case 72: bincode = "it";
            break;
            case 73: bincode = "iu";
            break;
            case 74: bincode = "ja";
            break;
            case 75: bincode = "jv";
            break;
            case 76: bincode = "ka";
            break;
            case 77: bincode = "kg";
            break;
            case 78: bincode = "ki";
            break;
            case 79: bincode = "kj";
            break;
            case 80: bincode = "kk";
            break;
            case 81: bincode = "kl";
            break;
            case 82: bincode = "km";
            break;
            case 83: bincode = "kn";
            break;
            case 84: bincode = "ko";
            break;
            case 85: bincode = "kr";
            break;
            case 86: bincode = "ks";
            break;
            case 87: bincode = "ku";
            break;
            case 88: bincode = "kv";
            break;
            case 89: bincode = "kw";
            break;
            case 90: bincode = "ky";
            break;
            case 91: bincode = "la";
            break;
            case 92: bincode = "lb";
            break;
            case 93: bincode = "lg";
            break;
            case 94: bincode = "li";
            break;
            case 95: bincode = "ln";
            break;
            case 96: bincode = "lo";
            break;
            case 97: bincode = "lt";
            break;
            case 98: bincode = "lu";
            break;
            case 99: bincode = "lv";
            break;
            case 100: bincode = "mg";
            break;
            case 101: bincode = "mh";
            break;
            case 102: bincode = "mi";
            break;
            case 103: bincode = "mk";
            break;
            case 104: bincode = "ml";
            break;
            case 105: bincode = "mn";
            break;
            case 106: bincode = "mr";
            break;
            case 107: bincode = "ms";
            break;
            case 108: bincode = "mt";
            break;
            case 109: bincode = "my";
            break;
            case 110: bincode = "na";
            break;
            case 111: bincode = "nb";
            break;
            case 112: bincode = "nd";
            break;
            case 113: bincode = "ne";
            break;
            case 114: bincode = "ng";
            break;
            case 115: bincode = "nl";
            break;
            case 116: bincode = "nn";
            break;
            case 117: bincode = "no";
            break;
            case 118: bincode = "nr";
            break;
            case 119: bincode = "nv";
            break;
            case 120: bincode = "ny";
            break;
            case 121: bincode = "oc";
            break;
            case 122: bincode = "oj";
            break;
            case 123: bincode = "om";
            break;
            case 124: bincode = "or";
            break;
            case 125: bincode = "os";
            break;
            case 126: bincode = "pa";
            break;
            case 127: bincode = "pi";
            break;
            case 128: bincode = "pl";
            break;
            case 129: bincode = "ps";
            break;
            case 130: bincode = "pt";
            break;
            case 131: bincode = "qu";
            break;
            case 132: bincode = "rm";
            break;
            case 133: bincode = "rn";
            break;
            case 134: bincode = "ro";
            break;
            case 135: bincode = "ru";
            break;
            case 136: bincode = "rw";
            break;
            case 137: bincode = "sa";
            break;
            case 138: bincode = "sc";
            break;
            case 139: bincode = "sd";
            break;
            case 140: bincode = "se";
            break;
            case 141: bincode = "sg";
            break;
            case 142: bincode = "si";
            break;
            case 143: bincode = "sk";
            break;
            case 144: bincode = "sl";
            break;
            case 145: bincode = "sm";
            break;
            case 146: bincode = "sn";
            break;
            case 147: bincode = "so";
            break;
            case 148: bincode = "sq";
            break;
            case 149: bincode = "sr";
            break;
            case 150: bincode = "ss";
            break;
            case 151: bincode = "st";
            break;
            case 152: bincode = "su";
            break;
            case 153: bincode = "sv";
            break;
            case 154: bincode = "sw";
            break;
            case 155: bincode = "ta";
            break;
            case 156: bincode = "te";
            break;
            case 157: bincode = "tg";
            break;
            case 158: bincode = "th";
            break;
            case 159: bincode = "ti";
            break;
            case 160: bincode = "tk";
            break;
            case 161: bincode = "tl";
            break;
            case 162: bincode = "tn";
            break;
            case 163: bincode = "to";
            break;
            case 164: bincode = "tr";
            break;
            case 165: bincode = "ts";
            break;
            case 166: bincode = "tt";
            break;
            case 167: bincode = "tw";
            break;
            case 168: bincode = "ty";
            break;
            case 169: bincode = "ug";
            break;
            case 170: bincode = "uk";
            break;
            case 171: bincode = "ur";
            break;
            case 172: bincode = "uz";
            break;
            case 173: bincode = "ve";
            break;
            case 174: bincode = "vi";
            break;
            case 175: bincode = "vo";
            break;
            case 176: bincode = "wa";
            break;
            case 177: bincode = "wo";
            break;
            case 178: bincode = "xh";
            break;
            case 179: bincode = "yi";
            break;
            case 180: bincode = "yo";
            break;
            case 181: bincode = "za";
            break;
            case 182: bincode = "zh";
            break; 
            }

            System.out.println("case " + i + ": \ntry {\n   System.out.println(GoogleTranslate.translate(\""+ bincode + "\",text));\n} catch (IOException e) {\n   e.printStackTrace();\n}\nbreak;\n");
            i++;
        } 
    }
}